target 'NRTC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'SideMenu','~> 4.0.0'
	pod 'ImageSlideshow', '~> 1.6'
        pod 'Alamofire', '~> 4.7'
	pod 'SDWebImage', '~> 4.0'
	pod 'SVProgressHUD'
	pod 'BadgeSwift', '~> 6.0'
	pod 'DLRadioButton', '~> 1.4'

end
